version: '3'

services:
  mypostgres:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
volumes:
  data: